name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install
        run: npm install --no-package-lock
      - name: Test
        run: npm test
      - name: Report
        run: mkdir -p coverage && npx nyc report --reporter=text-lcov > coverage/lcov.info
      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: 'script -q -e -c "bash {0}"'
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER }}
          CONVENTIONAL_GITHUB_RELEASER_TOKEN=${{ secrets.CONVENTIONAL_GITHUB_RELEASER_TOKEN }} npm run release
